### ISSUE TITLE
Latest Zxing library causes an issue

### ISSUE THREAD

**Issue by iTerminate** [AdvancedPhotonSource/ComponentDB-Mobile#3]
Solution has been implemented by downgrading zxing 2.3.2. 

Right after the permission for camera is approved the scanning event is not fired until after the user leaves the scanner page and returns to it. 

Does not work with version 2.4.1. Watch for issue to be closed: https://github.com/Redth/ZXing.Net.Mobile/issues/717

**Comment by iTerminate** [comment]
The solution is temporary, test after zxing closes the referenced issue.

**Comment by iTerminate** [comment]
No longer an issue.

**Comment by TonyC5** [comment]
@iTerminate "No longer an issue" with which version?  I still have the problem with version 2.4.1 and Android (not iOS) so I'm using version 2.3.2 without issues (with Xamarin.Forms 5.0.0.2012, Target Framework: Android 10 (Q), Minimum Android Version: Android 4.4).  I build with Visual Studio Community 2019 for Mac on Big Sur 11.5.1.

**Comment by iTerminate** [comment]
Yes I believe that was my solution was to downgrade to 2.3.2
